version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:9.0.1-11-jdk-node-browsers
    steps:
      - checkout
      - run: ./gradlew build
  dependencies:
    override:
      - chmod +x gradlew
      - ./gradlew dependencies
  test:
    docker:
      - image: circleci/openjdk:9.0.1-11-jdk-node-browsers
    steps:
      - checkout
      - run: ./gradlew test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test